-- Fix quest 29932 "The Temple of the Jade Serpent" (青龙寺): the kite ride
-- option from Kitemaster Shoku never appeared, and the final objective
-- (256152, talk to Elder Sage) had no credit source at all.
--
-- Quest flow (445): Foreman Raike (59391) hands out 29932; the player talks to
-- Kitemaster Shoku (59392) and picks "将我送往青龙寺." (fly me to the temple),
-- riding Shoku's kite to the temple entrance; there the player speaks with the
-- Elder Sage (56782, "大贤者", quest ender) and hands the quest in.
--
-- Bug 1 - kite option hidden forever:
--   gossip menu 59392 option 1 was gated by a `conditions` row using
--   ConditionTypeOrReference = 28 = CONDITION_QUEST_COMPLETE ("all objectives
--   done, quest not yet rewarded").  The player must use this very option to
--   TRAVEL to the temple and complete the objective (256152) - at ride time
--   the objective is obviously not complete, so the condition could never be
--   true and the option was permanently hidden (dead lock).
--
--   Fix: gate the option on ConditionTypeOrReference = 9 =
--   CONDITION_QUESTTAKEN (visible while the quest is active/in progress).
--
--   The same table also gated option 0 "I have the jade shipment." (quest
--   30495) on CONDITION_QUEST_COMPLETE.  That option became obsolete in an
--   earlier update: the 30495 delivery credit is granted directly on the
--   gossip-hello interaction (SMART_EVENT_GOSSIP_HELLO ->
--   SMART_ACTION_CALL_KILLEDMONSTER, identical to the other three foremen),
--   and the old menu-select spell-cast chain on option 0 was removed.  A menu
--   option without a script would confuse players, so option 0 (menu row, zhCN
--   locale row, conditions row) is deleted; the kite option keeps OptionID 1,
--   which the existing SmartAI GOSSIP_SELECT script (sender 59392 / action 1
--   -> teleport to the temple) already expects.
--

-- NOTE: the objective credit itself (kill credit 57290) is handled in
-- 2026_09_23_05_world_restore_kite_ride_and_fix_sage_credit.sql, where it is
-- correctly placed on Elder Sage Wind-Yi (57242) - the talk target outside the
-- temple entrance - together with the restored kite-ride mechanics (this file
-- only covers the menu-option visibility fixes).
